name: WakaTime Stats Updater
on:
  schedule:
    - cron: '0 18 * * *'  # UTC时间每天18点运行
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 必须授予写入权限（网页5）
    steps:
      - uses: actions/checkout@v4

      - name: Generate WakaTime Stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SECTION_NAME: waka
          SHOW_OS: true
          SHOW_PROJECTS: true
          DEBUG_LOGGING: true  # 开启调试日志